version: '3'
services:
  recipe-book-api:
    build:
      context: ./api
    ports:
      - "3080:3080"
    container_name: recipe-book-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
    links:
        - postgres
  recipe-book-ui:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    container_name: recipe-book-ui
    stdin_open: true
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data